apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: gaocheng001
    provider: https://github.com
    providerKind: github
    repositories:
    - name: and
    - name: boozsoftphp
    - name: helloa
    - name: wodenode
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
